Name : Abhinav Kumar,
Phone number : 7879557562,
email : singhabhinav8074@gmail.com

## RUN ALL CELLS AND THE OUTPUT WILL BE GENERATED IN "submission.csv" in path "/content/gibots/submission.csv"

In [ ]:
%cd /content

[WinError 2] The system cannot find the file specified: '/content'
C:\Users\Abhishek Kumar\Downloads\gibots-main\gibots-main

In [2]:
!git clone https://github.com/ABHINAV12KUMAR/GiBots_A.git

fatal: destination path 'GiBots_A' already exists and is not an empty directory.

In [ ]:
%cd Gibots

C:\Users\Abhishek Kumar\Downloads\gibots-main\gibots-main\Gibots

In [4]:
import pandas as pd
import numpy as np

In [6]:
train_labels = pd.read_csv("trainLabels.csv")
train_data = pd.read_csv("train.csv")
test_data = pd.read_csv("test.csv",header = None)
sample = pd.read_csv("sampleSubmission_small.csv")

In [7]:
train_data

,id,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x136,x137,x138,x139,x140,x141,x142,x143,x144,x145
0,1,NO,NO,dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=,GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=,0.576561,0.073139,0.481394,0.115697,0.472474,...,0.0,0.810,3306,4676,YES,NO,YES,2,0.375535,0.464610
1,2,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.510,4678,3306,YES,NO,YES,4,0.741682,0.593630
2,3,NO,NO,ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=,X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=,1.341803,0.051422,0.935572,0.041440,0.501710,...,0.0,0.850,4678,3306,NO,NO,NO,1,0.776467,0.493159
3,4,YES,NO,BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=,YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=,0.653912,0.041471,0.940787,0.090851,0.556564,...,0.0,0.945,3306,4678,NO,NO,YES,3,0.168234,0.546582
4,5,NO,NO,RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=,3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=,1.415919,0.000000,1.000000,0.000000,0.375297,...,0.0,1.000,1263,892,NO,NO,NO,1,0.246637,0.361045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,9995,NO,NO,jComfqYTXYSeH3GvqcOhwPmldb+BCdVJDKKDNkdtw2w=,Kr2CC15nSwDjdpyAeVh4vOuIaHuC/Q7cL9BAK28JoG8=,1.207136,0.082855,0.918960,0.313880,0.495189,...,0.0,0.810,4677,3307,YES,NO,YES,1,0.502268,0.486637
9995,9996,NO,NO,Pr5enXjzVzVjZziZxrDcgnyu6CLUftmEbnp6TctyJbU=,YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=,1.414798,0.000000,1.000000,0.000000,0.357369,...,0.0,1.000,1262,892,YES,NO,YES,15,0.890135,0.346276
9996,9997,YES,YES,9Avs0tL1zvH7Xx41z2UqrXs11/4IWLmqRAodLt/SKjQ=,WV5vAHFyqkeuyFB5KVNGFOBuwjkUGKYc8wh9QfpVzAA=,1.413677,0.000000,1.000000,0.000000,0.668517,...,0.0,1.000,1261,892,YES,NO,YES,5,0.726457,0.659001
9997,9998,NO,NO,9zkXU3f6YnRPjsWi3lKSCLseIGrleg00tpRI4OplABw=,gOZBAoajyr6i7GgON0N7q5+KE4JTwH3OUM0lZOWMuG8=,1.294118,0.000000,1.000000,0.000000,0.570707,...,1.0,1.000,1188,918,NO,NO,NO,3,0.450980,0.561448
9998,9999,YES,YES,MZZbXga8gvaCBqWpzrh2iKdOkcsz/bG/z4BVjUnqWT0=,YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=,0.660897,0.042735,0.946581,0.086966,0.510278,...,0.0,0.880,3308,4680,YES,NO,YES,0,0.604274,0.499395

In [8]:
train_data = train_data.iloc[:9999,1:]
train_labels = train_labels.iloc[:9999,1:]

In [9]:
traindata_columns = train_data.columns
traindata_columns

Index(['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10',
       ...
       'x136', 'x137', 'x138', 'x139', 'x140', 'x141', 'x142', 'x143', 'x144',
       'x145'],
      dtype='object', length=145)

In [10]:
train_data.head()

,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,...,x136,x137,x138,x139,x140,x141,x142,x143,x144,x145
0,NO,NO,dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=,GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=,0.576561,0.073139,0.481394,0.115697,0.472474,YES,...,0.0,0.810,3306,4676,YES,NO,YES,2,0.375535,0.464610
1,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,...,0.0,0.510,4678,3306,YES,NO,YES,4,0.741682,0.593630
2,NO,NO,ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=,X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=,1.341803,0.051422,0.935572,0.041440,0.501710,NO,...,0.0,0.850,4678,3306,NO,NO,NO,1,0.776467,0.493159
3,YES,NO,BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=,YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=,0.653912,0.041471,0.940787,0.090851,0.556564,YES,...,0.0,0.945,3306,4678,NO,NO,YES,3,0.168234,0.546582
4,NO,NO,RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=,3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=,1.415919,0.000000,1.000000,0.000000,0.375297,NO,...,0.0,1.000,1263,892,NO,NO,NO,1,0.246637,0.361045

In [11]:
train_labels.head()

,y1,y2,y3,y4,y5,y6,y7,y8,y9,y10,...,y24,y25,y26,y27,y28,y29,y30,y31,y32,y33
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [12]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Columns: 145 entries, x1 to x145
dtypes: float64(55), int64(30), object(60)
memory usage: 11.1+ MB

In [13]:
train_data.isnull().sum()

x1      1426
x2      1426
x3      1426
x4      1426
x5         0
        ...
x141       0
x142       0
x143       0
x144       0
x145       0
Length: 145, dtype: int64

In [14]:
train_data.describe()

,x5,x6,x7,x8,x9,x15,x16,x17,x18,x19,...,x133,x134,x135,x136,x137,x138,x139,x143,x144,x145
count,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000,9999.000000
mean,0.964933,0.053623,0.791668,0.172705,0.448091,6.056806,0.418593,4.483448,8.073907,0.821911,...,9.291529,8.800880,0.933771,0.056523,0.924781,2669.290629,2142.907091,3.667767,0.519482,0.505084
std,0.524688,0.128503,0.353194,0.329020,0.300549,8.756490,0.294579,4.388639,7.032278,0.338406,...,7.576648,6.584598,0.069921,1.520931,0.118496,1588.220409,1386.559408,11.014722,0.270886,0.256323
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.176169,...,1.000000,0.000000,-0.098334,-17.000000,0.000000,892.000000,838.000000,0.000000,0.021635,0.001327
25%,0.642796,0.000000,0.831299,0.000000,0.199617,1.000000,0.165599,2.000000,3.000000,0.929372,...,4.000000,4.000000,0.916144,0.000000,0.880000,1262.000000,892.000000,1.000000,0.267939,0.306031
50%,1.285541,0.000000,0.960637,0.000000,0.439504,3.000000,0.395740,4.000000,7.000000,0.962492,...,7.000000,7.000000,0.949552,0.000000,1.000000,1263.000000,918.000000,2.000000,0.517937,0.484561
75%,1.414798,0.058076,1.000000,0.151543,0.682880,7.000000,0.683908,6.000000,11.000000,0.980942,...,13.000000,12.000000,0.972222,0.000000,1.000000,4672.000000,3308.000000,5.000000,0.759242,0.707324
max,1.474916,0.992745,1.000000,1.393289,1.098257,88.000000,1.180828,132.000000,118.000000,0.999773,...,84.000000,118.000000,0.999947,23.000000,1.000000,5217.000000,6622.000000,697.000000,1.238562,1.086371

In [15]:
train_data.duplicated().sum()

95

In [16]:
# Remove Duplicates from train_data and also remove the corresponding rows in train_labels as well
original_indices = train_data.index
train_data = train_data.drop_duplicates()
dropped_indices = original_indices.difference(train_data.index)
print("Total rows dropped : " + str(len(dropped_indices)))
train_labels = train_labels.drop(dropped_indices)

Total rows dropped : 95

In [17]:
train_data.corr

<bound method DataFrame.corr of        x1   x2                                            x3  \
0      NO   NO  dqOiM6yBYgnVSezBRiQXs9bvOFnRqrtIoXRIElxD7g8=
1     NaN  NaN                                           NaN
2      NO   NO  ib4VpsEsqJHzDiyL0dZLQ+xQzDPrkxE+9T3mx5fv2wI=
3     YES   NO  BfrqME7vdLw3suQp6YAT16W2piNUmpKhMzuDrVrFQ4w=
4      NO   NO  RTjsrrR8DTlJyaIP9Q3Z8s0zseqlVQTrlSe97GCWfbk=
...   ...  ...                                           ...
9994   NO   NO  jComfqYTXYSeH3GvqcOhwPmldb+BCdVJDKKDNkdtw2w=
9995   NO   NO  Pr5enXjzVzVjZziZxrDcgnyu6CLUftmEbnp6TctyJbU=
9996  YES  YES  9Avs0tL1zvH7Xx41z2UqrXs11/4IWLmqRAodLt/SKjQ=
9997   NO   NO  9zkXU3f6YnRPjsWi3lKSCLseIGrleg00tpRI4OplABw=
9998  YES  YES  MZZbXga8gvaCBqWpzrh2iKdOkcsz/bG/z4BVjUnqWT0=

                                                x4        x5        x6  \
0     GNjrXXA3SxbgD0dTRblAPO9jFJ7AIaZnu/f48g5XSUk=  0.576561  0.073139
1                                              NaN  0.000000  0.000000
2     X6dDAI/DZOWvu0Dg6gCgRoNr2vTUz/mc4SdHTNUPS38=  1.341803  0.051422
3     YGCdISifn4fLao/ASKdZFhGIq23oqzfSbUVb6px1pig=  0.653912  0.041471
4     3yK2OPj1uYDsoMgsxsjY1FxXkOllD8Xfh20VYGqT+nU=  1.415919  0.000000
...                                            ...       ...       ...
9994  Kr2CC15nSwDjdpyAeVh4vOuIaHuC/Q7cL9BAK28JoG8=  1.207136  0.082855
9995  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  1.414798  0.000000
9996  WV5vAHFyqkeuyFB5KVNGFOBuwjkUGKYc8wh9QfpVzAA=  1.413677  0.000000
9997  gOZBAoajyr6i7GgON0N7q5+KE4JTwH3OUM0lZOWMuG8=  1.294118  0.000000
9998  YvZUuCDjLu9VvkCdBWgARWQrvm+FSXgxp0zIrMjcLBc=  0.660897  0.042735

            x7        x8        x9  x10  ... x136   x137  x138  x139  x140  \
0     0.481394  0.115697  0.472474  YES  ...  0.0  0.810  3306  4676   YES
1     0.000000  0.000000  0.000000  NaN  ...  0.0  0.510  4678  3306   YES
2     0.935572  0.041440  0.501710   NO  ...  0.0  0.850  4678  3306    NO
3     0.940787  0.090851  0.556564  YES  ...  0.0  0.945  3306  4678    NO
4     1.000000  0.000000  0.375297   NO  ...  0.0  1.000  1263   892    NO
...        ...       ...       ...  ...  ...  ...    ...   ...   ...   ...
9994  0.918960  0.313880  0.495189   NO  ...  0.0  0.810  4677  3307   YES
9995  1.000000  0.000000  0.357369  YES  ...  0.0  1.000  1262   892   YES
9996  1.000000  0.000000  0.668517  YES  ...  0.0  1.000  1261   892   YES
9997  1.000000  0.000000  0.570707   NO  ...  1.0  1.000  1188   918    NO
9998  0.946581  0.086966  0.510278  YES  ...  0.0  0.880  3308  4680   YES

      x141  x142  x143      x144      x145
0       NO   YES     2  0.375535  0.464610
1       NO   YES     4  0.741682  0.593630
2       NO    NO     1  0.776467  0.493159
3       NO   YES     3  0.168234  0.546582
4       NO    NO     1  0.246637  0.361045
...    ...   ...   ...       ...       ...
9994    NO   YES     1  0.502268  0.486637
9995    NO   YES    15  0.890135  0.346276
9996    NO   YES     5  0.726457  0.659001
9997    NO    NO     3  0.450980  0.561448
9998    NO   YES     0  0.604274  0.499395

[9904 rows x 145 columns]>

In [18]:
# Trying to find the columns that are categorical and needs to be encoded
encode_columns = []
for index,element in enumerate(train_data.iloc[0,:]):
  if element == 'YES' or element == 'NO':
    encode_columns.append("x" + str(index+1))
    # print(index+1)
print(encode_columns)

['x1', 'x2', 'x10', 'x11', 'x12', 'x13', 'x14', 'x24', 'x25', 'x26', 'x30', 'x31', 'x32', 'x33', 'x41', 'x42', 'x43', 'x44', 'x45', 'x55', 'x56', 'x57', 'x62', 'x63', 'x71', 'x72', 'x73', 'x74', 'x75', 'x85', 'x86', 'x87', 'x92', 'x93', 'x101', 'x102', 'x103', 'x104', 'x105', 'x115', 'x116', 'x117', 'x126', 'x127', 'x128', 'x129', 'x130', 'x140', 'x141', 'x142']

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,f1_score,accuracy_score,hamming_loss,precision_score,recall_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [20]:
# Feature Selection
train_data = train_data.drop(columns=["x3","x4","x34","x35","x61","x64","x65","x91","x94","x95"])

In [21]:
train_data

,x1,x2,x5,x6,x7,x8,x9,x10,x11,x12,...,x136,x137,x138,x139,x140,x141,x142,x143,x144,x145
0,NO,NO,0.576561,0.073139,0.481394,0.115697,0.472474,YES,NO,NO,...,0.0,0.810,3306,4676,YES,NO,YES,2,0.375535,0.464610
1,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.0,0.510,4678,3306,YES,NO,YES,4,0.741682,0.593630
2,NO,NO,1.341803,0.051422,0.935572,0.041440,0.501710,NO,NO,YES,...,0.0,0.850,4678,3306,NO,NO,NO,1,0.776467,0.493159
3,YES,NO,0.653912,0.041471,0.940787,0.090851,0.556564,YES,NO,NO,...,0.0,0.945,3306,4678,NO,NO,YES,3,0.168234,0.546582
4,NO,NO,1.415919,0.000000,1.000000,0.000000,0.375297,NO,NO,YES,...,0.0,1.000,1263,892,NO,NO,NO,1,0.246637,0.361045
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9994,NO,NO,1.207136,0.082855,0.918960,0.313880,0.495189,NO,NO,NO,...,0.0,0.810,4677,3307,YES,NO,YES,1,0.502268,0.486637
9995,NO,NO,1.414798,0.000000,1.000000,0.000000,0.357369,YES,NO,NO,...,0.0,1.000,1262,892,YES,NO,YES,15,0.890135,0.346276
9996,YES,YES,1.413677,0.000000,1.000000,0.000000,0.668517,YES,NO,NO,...,0.0,1.000,1261,892,YES,NO,YES,5,0.726457,0.659001
9997,NO,NO,1.294118,0.000000,1.000000,0.000000,0.570707,NO,NO,NO,...,1.0,1.000,1188,918,NO,NO,NO,3,0.450980,0.561448
9998,YES,YES,0.660897,0.042735,0.946581,0.086966,0.510278,YES,NO,NO,...,0.0,0.880,3308,4680,YES,NO,YES,0,0.604274,0.499395

In [22]:
# Applying train_test split
X_train, X_val, y_train, y_val = train_test_split(train_data, train_labels, test_size=0.2, random_state=42)

In [23]:
X_train

,x1,x2,x5,x6,x7,x8,x9,x10,x11,x12,...,x136,x137,x138,x139,x140,x141,x142,x143,x144,x145
1469,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.0,0.860,4672,3306,YES,NO,YES,0,0.869933,0.717894
1667,YES,NO,1.164247,0.156685,0.537205,1.150635,0.823202,YES,NO,YES,...,0.0,0.920,4672,3306,YES,NO,YES,0,0.245614,0.814640
1417,NO,NO,1.406826,0.047720,0.951072,1.330112,0.956178,YES,NO,NO,...,0.0,0.830,4678,3311,NO,NO,NO,18,0.599215,0.950406
8469,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,...,0.0,0.890,4400,3400,YES,NO,YES,0,0.711765,0.309773
4727,NO,NO,1.415919,0.000000,1.000000,0.000000,0.935075,NO,NO,NO,...,-1.0,1.000,1263,892,NO,NO,NO,8,0.747758,0.928741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5770,NO,NO,1.413677,0.000000,1.000000,0.000000,0.188739,NO,NO,NO,...,-1.0,1.000,1261,892,NO,NO,NO,2,0.802691,0.176844
5222,YES,NO,0.661752,0.042949,0.947009,0.087821,0.923821,YES,NO,NO,...,0.0,0.900,3308,4680,NO,NO,YES,2,0.170085,0.912938
5422,NO,NO,1.323556,0.087693,0.915634,0.325370,0.932421,YES,NO,NO,...,0.0,0.840,4676,3307,YES,NO,YES,0,0.661324,0.924936
860,NO,NO,1.415919,0.000000,1.000000,0.000000,0.760095,YES,NO,NO,...,0.0,1.000,1263,892,NO,NO,NO,1,0.752242,0.749010
7323,NO,NO,0.698730,0.072898,0.925287,0.399577,0.439050,NO,NO,YES,...,0.0,0.935,4676,3306,NO,NO,NO,1,0.286751,0.429855

In [24]:
# Handling Categorical values "YES" or "NO"
from sklearn.compose import ColumnTransformer

non_encode_cols = [col for col in X_train.columns if col not in encode_columns]

transformer = ColumnTransformer(transformers = [
    ('tnf1', OrdinalEncoder(), encode_columns)
],remainder='passthrough')

encode_data1 = transformer.fit_transform(X_train)
encode_data2 = transformer.transform(X_val)

print(encode_data1)

transformed_xtrain = pd.DataFrame(encode_data1, columns= encode_columns + non_encode_cols)
transformed_xval = pd.DataFrame(encode_data2, columns= encode_columns + non_encode_cols)

[[        nan         nan         nan ...  0.          0.86993345
   0.71789384]
 [ 1.          0.          1.         ...  0.          0.24561404
   0.81464041]
 [ 0.          0.          1.         ... 18.          0.59921474
   0.95040616]
 ...
 [ 0.          0.          1.         ...  0.          0.66132446
   0.92493584]
 [ 0.          0.          1.         ...  1.          0.75224215
   0.74901029]
 [ 0.          0.          0.         ...  1.          0.28675136
   0.42985458]]

In [25]:
transformed_xtrain

,x1,x2,x10,x11,x12,x13,x14,x24,x25,x26,...,x133,x134,x135,x136,x137,x138,x139,x143,x144,x145
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,2.0,0.961887,0.0,0.860,4672.0,3306.0,0.0,0.869933,0.717894
1,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,...,2.0,4.0,0.982456,0.0,0.920,4672.0,3306.0,0.0,0.245614,0.814640
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,5.0,38.0,0.978254,0.0,0.830,4678.0,3311.0,18.0,0.599215,0.950406
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,0.996471,0.0,0.890,4400.0,3400.0,0.0,0.711765,0.309773
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.0,11.0,0.938341,-1.0,1.000,1263.0,892.0,8.0,0.747758,0.928741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7918,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,15.0,3.0,0.897982,-1.0,1.000,1261.0,892.0,2.0,0.802691,0.176844
7919,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,18.0,14.0,0.915789,0.0,0.900,3308.0,4680.0,2.0,0.170085,0.912938
7920,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,6.0,4.0,0.964318,0.0,0.840,4676.0,3307.0,0.0,0.661324,0.924936
7921,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,5.0,3.0,0.961883,0.0,1.000,1263.0,892.0,1.0,0.752242,0.749010
7922,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,10.0,13.0,0.933869,0.0,0.935,4676.0,3306.0,1.0,0.286751,0.429855

In [26]:
# Missing Value Imputation

transformer2 = ColumnTransformer(transformers = [
    ('tnf2', SimpleImputer(strategy="most_frequent"), encode_columns)
],remainder='passthrough')

impute_data1 = transformer2.fit_transform(transformed_xtrain)
impute_data2 = transformer2.transform(transformed_xval)

print(impute_data1)

transformed_xtrain = pd.DataFrame(impute_data1, columns= encode_columns + non_encode_cols)
transformed_xval = pd.DataFrame(impute_data2, columns= encode_columns + non_encode_cols)

[[ 0.          0.          0.         ...  0.          0.86993345
   0.71789384]
 [ 1.          0.          1.         ...  0.          0.24561404
   0.81464041]
 [ 0.          0.          1.         ... 18.          0.59921474
   0.95040616]
 ...
 [ 0.          0.          1.         ...  0.          0.66132446
   0.92493584]
 [ 0.          0.          1.         ...  1.          0.75224215
   0.74901029]
 [ 0.          0.          0.         ...  1.          0.28675136
   0.42985458]]

In [27]:
from sklearn.ensemble import RandomForestClassifier # Works the best till now
from sklearn.tree import DecisionTreeClassifier # gives better accuracy
from sklearn.neural_network import MLPClassifier # Not good model , need more data
from sklearn.linear_model import LogisticRegression
import warnings

In [28]:
!pip install scikit-multilearn

Requirement already satisfied: scikit-multilearn in c:\users\abhishek kumar\anaconda3\lib\site-packages (0.2.0)

In [29]:
from skmultilearn.problem_transform import BinaryRelevance,ClassifierChain,LabelPowerset

In [30]:
# Trying the accuracy of all the models and chosing the best model
def try_models(x_train,y_train,x_test,y_test,model_name = RandomForestClassifier(n_estimators=100 , random_state=42),multi_label_model = LabelPowerset):

  warnings.filterwarnings("ignore")
  model =  multi_label_model(model_name)
  print(model.fit(x_train, y_train))
  y_pred = model.predict(x_test)

  if multi_label_model == MultiOutputClassifier:
    # Because MultiOutputClassifier model has no metrics hence we have to create them ourselves
    y_val_np = np.array(y_val)
    y_pred_np = np.array(y_pred)

    # Calculate Hamming Loss
    hamming_loss_value = np.mean(np.not_equal(y_val_np, y_pred_np))
    print("Hamming Loss is : " + str(hamming_loss_value))

    # Calculating Accuracy
    temp = 0
    for i in range(y_val.values.shape[0]):
        temp += sum(np.logical_and(y_val.values[i], y_pred[i])) / sum(np.logical_or(y_val.values[i], y_pred[i]))
    print("Accuracy is : " + str(temp / y_val.values.shape[0]))

    # Calculating 0-1 Loss
    loss01 = np.any(y_val != y_pred, axis=1).mean()
    print("0-1 Loss is : " + str(loss01))

    # Calculating Recall
    temp = 0
    for i in range(y_val.values.shape[0]):
        if sum(y_val.values[i]) == 0:
            continue
        temp+= sum(np.logical_and(y_val.values[i], y_pred[i]))/ sum(y_val.values[i])
    print("Recall is : " + str(temp/ y_val.values.shape[0]))

    # Calculating Precision
    temp = 0
    for i in range(y_val.values.shape[0]):
        if sum(y_pred[i]) == 0:
            continue
        temp+= sum(np.logical_and(y_val.values[i], y_pred[i]))/ sum(y_pred[i])
    print("Precision is : " + str(temp/ y_val.values.shape[0]))

    return model

  print("Accuracy is : " + str(accuracy_score(y_val,y_pred)))
  print("Hamming Loss is : " + str(hamming_loss(y_val,y_pred)))
  print("Recall is : " + str(recall_score(y_val,y_pred,average='weighted')))
  print("Precision is : " + str(precision_score(y_val,y_pred,average = 'weighted')))
  print("F1 Score is : " + str(f1_score(y_val,y_pred,average = 'weighted')))
  warnings.resetwarnings()

  return model

## **The Best accuracy is achieved by multi_label_models = LabelPowerset and model_name = RandomForestClassifier **

In [31]:
# The possible multi_label_models are : LabelPowerset,BinaryRelevance,ClassifierChain,MultiOutputClassifier
# Suggested model_name are : MLPClassifier,DecisionTreeClassifier,RandomForestClassifier

model = try_models(x_train=transformed_xtrain,x_test=transformed_xval,y_train= y_train,y_test= y_val)

# After applying GridSearch CV , the best model combinations are the default values i.e. multi_label_models = LabelPowerset , model_name = RandomForestClassifier

LabelPowerset(classifier=RandomForestClassifier(random_state=42),
              require_dense=[True, True])
Accuracy is : 0.7960625946491671
Hamming Loss is : 0.012987012987012988
Recall is : 0.7988245931283906
Precision is : 0.8220755966032699
F1 Score is : 0.7887582698260973

In [32]:
model.predict(transformed_xtrain.iloc[:3,0:]).toarray()

C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\base.py:432: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\pandas\core\algorithms.py:1814: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  return lib.map_infer(values, mapper, convert=convert)
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

In [33]:
# Function that will provide us with the output for the given input
def get_output(model , test_data):

  test_data.columns = traindata_columns.insert(0,"id")
  test_data = test_data.drop([0])
  # Feature Selection of the input
  test_data = test_data.drop(columns=["x3","x4","x34","x35","x61","x64","x65","x91","x94","x95"])
  # Encoding Categorical data
  encode_data3 = transformer.transform(test_data)
  transformed_xtest = pd.DataFrame(encode_data3, columns= encode_columns + non_encode_cols)
  # Missing value imputation of input
  impute_data4 = transformer2.transform(transformed_xtest)
  transformed_xtest = pd.DataFrame(impute_data4, columns= encode_columns + non_encode_cols)
  # Model Prediction
  output = model.predict(transformed_xtest)
  return output.toarray()

In [34]:
answer = get_output(model,test_data.copy())

C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:605: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
C:\Users\Abhishek Kumar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:614: DeprecationWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):

In [35]:
# Changing the output generated in the form that is mentioned in the samplesubmission_small.csv
output_dataset = pd.DataFrame(columns = ["id_label","pred"])

for ind1,element in enumerate(answer):
  for ind2,num in enumerate(element):
    new_data = {
        "id_label" : str(test_data.iloc[ind1,0]) + "_y" + str(ind2+1),
        "pred" : num
    }
    # Convert the new data to a DataFrame
    new_row = pd.DataFrame([new_data])

    # Concatenate the existing DataFrame with the new row
    output_dataset = pd.concat([output_dataset, new_row], ignore_index=True)

In [36]:
output_dataset

          id_label pred
0       1698001_y1    0
1       1698001_y2    0
2       1698001_y3    0
3       1698001_y4    0
4       1698001_y5    0
...            ...  ...
65962  1699999_y29    0
65963  1699999_y30    0
65964  1699999_y31    0
65965  1699999_y32    0
65966  1699999_y33    1

[65967 rows x 2 columns]

In [ ]:
output_dataset.to_csv('/content/Gibots/submission.csv',index = False)